// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package search

import (
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

const PERF_COUNTER_VAL_TYPE_LONG = 0
const PERF_COUNTER_VAL_TYPE_DOUBLE = 1
const PERF_COUNTER_VAL_TYPE_STRING = 2

func init() {
}
